/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as InstalarTokenRouteImport } from './routes/instalar/$token'
import { Route as AuthenticatedTiEnterpriseCallbackRouteImport } from './routes/_authenticated/ti/enterprise-callback'
import { Route as ApiPublicAgentDeviceInfoRouteImport } from './routes/api/public/agent/device-info'
import { Route as ApiPublicAgentEnrollRouteImport } from './routes/api/public/agent/enroll'
import { Route as ApiPublicAgentHeartbeatRouteImport } from './routes/api/public/agent/heartbeat'
import { Route as ApiPublicAgentSessionRouteImport } from './routes/api/public/agent/session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const InstalarTokenRoute = InstalarTokenRouteImport.update({
  id: '/instalar/$token',
  path: '/instalar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTiEnterpriseCallbackRoute =
  AuthenticatedTiEnterpriseCallbackRouteImport.update({
    id: '/ti/enterprise-callback',
    path: '/ti/enterprise-callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAgentDeviceInfoRoute =
  ApiPublicAgentDeviceInfoRouteImport.update({
    id: '/api/public/agent/device-info',
    path: '/api/public/agent/device-info',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentEnrollRoute = ApiPublicAgentEnrollRouteImport.update({
  id: '/api/public/agent/enroll',
  path: '/api/public/agent/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentHeartbeatRoute = ApiPublicAgentHeartbeatRouteImport.update({
  id: '/api/public/agent/heartbeat',
  path: '/api/public/agent/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentSessionRoute = ApiPublicAgentSessionRouteImport.update({
  id: '/api/public/agent/session',
  path: '/api/public/agent/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/instalar/$token': typeof InstalarTokenRoute
  '/ti/enterprise-callback': typeof AuthenticatedTiEnterpriseCallbackRoute
  '/api/public/agent/device-info': typeof ApiPublicAgentDeviceInfoRoute
  '/api/public/agent/enroll': typeof ApiPublicAgentEnrollRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/agent/session': typeof ApiPublicAgentSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/instalar/$token': typeof InstalarTokenRoute
  '/ti/enterprise-callback': typeof AuthenticatedTiEnterpriseCallbackRoute
  '/api/public/agent/device-info': typeof ApiPublicAgentDeviceInfoRoute
  '/api/public/agent/enroll': typeof ApiPublicAgentEnrollRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/agent/session': typeof ApiPublicAgentSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/instalar/$token': typeof InstalarTokenRoute
  '/_authenticated/ti/enterprise-callback': typeof AuthenticatedTiEnterpriseCallbackRoute
  '/api/public/agent/device-info': typeof ApiPublicAgentDeviceInfoRoute
  '/api/public/agent/enroll': typeof ApiPublicAgentEnrollRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/agent/session': typeof ApiPublicAgentSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/painel'
    | '/instalar/$token'
    | '/ti/enterprise-callback'
    | '/api/public/agent/device-info'
    | '/api/public/agent/enroll'
    | '/api/public/agent/heartbeat'
    | '/api/public/agent/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/painel'
    | '/instalar/$token'
    | '/ti/enterprise-callback'
    | '/api/public/agent/device-info'
    | '/api/public/agent/enroll'
    | '/api/public/agent/heartbeat'
    | '/api/public/agent/session'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/painel'
    | '/instalar/$token'
    | '/_authenticated/ti/enterprise-callback'
    | '/api/public/agent/device-info'
    | '/api/public/agent/enroll'
    | '/api/public/agent/heartbeat'
    | '/api/public/agent/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InstalarTokenRoute: typeof InstalarTokenRoute
  ApiPublicAgentDeviceInfoRoute: typeof ApiPublicAgentDeviceInfoRoute
  ApiPublicAgentEnrollRoute: typeof ApiPublicAgentEnrollRoute
  ApiPublicAgentHeartbeatRoute: typeof ApiPublicAgentHeartbeatRoute
  ApiPublicAgentSessionRoute: typeof ApiPublicAgentSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/instalar/$token': {
      id: '/instalar/$token'
      path: '/instalar/$token'
      fullPath: '/instalar/$token'
      preLoaderRoute: typeof InstalarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ti/enterprise-callback': {
      id: '/_authenticated/ti/enterprise-callback'
      path: '/ti/enterprise-callback'
      fullPath: '/ti/enterprise-callback'
      preLoaderRoute: typeof AuthenticatedTiEnterpriseCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/agent/device-info': {
      id: '/api/public/agent/device-info'
      path: '/api/public/agent/device-info'
      fullPath: '/api/public/agent/device-info'
      preLoaderRoute: typeof ApiPublicAgentDeviceInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/enroll': {
      id: '/api/public/agent/enroll'
      path: '/api/public/agent/enroll'
      fullPath: '/api/public/agent/enroll'
      preLoaderRoute: typeof ApiPublicAgentEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/heartbeat': {
      id: '/api/public/agent/heartbeat'
      path: '/api/public/agent/heartbeat'
      fullPath: '/api/public/agent/heartbeat'
      preLoaderRoute: typeof ApiPublicAgentHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/session': {
      id: '/api/public/agent/session'
      path: '/api/public/agent/session'
      fullPath: '/api/public/agent/session'
      preLoaderRoute: typeof ApiPublicAgentSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedTiEnterpriseCallbackRoute: typeof AuthenticatedTiEnterpriseCallbackRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedTiEnterpriseCallbackRoute:
    AuthenticatedTiEnterpriseCallbackRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InstalarTokenRoute: InstalarTokenRoute,
  ApiPublicAgentDeviceInfoRoute: ApiPublicAgentDeviceInfoRoute,
  ApiPublicAgentEnrollRoute: ApiPublicAgentEnrollRoute,
  ApiPublicAgentHeartbeatRoute: ApiPublicAgentHeartbeatRoute,
  ApiPublicAgentSessionRoute: ApiPublicAgentSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
